//
// Created by lukaa on 5.1.2025..
//

#ifndef SPRITEFONTLOADER_H
#define SPRITEFONTLOADER_H

#include "core/fonts/SpriteFont.h"
#include <tinyxml2.h>

namespace mars {
    class Framework;


    class SpriteFontLoader {
    public:
        //! Construct a new SpriteFontLoader object.
          //! @param framework The framework.
        explicit SpriteFontLoader(Framework &framework);

        //! Finds and loads a snowb sprite font.
        //! These fonts are generated by the snowb font generator.
        //! For more <a href="https://snowb.org/">snowb.org</a>.
        //! @param xmlPath The path to the xml file.
        //! @param texturePath The path to the texture file. If null, texture path will be extracted from the xml file.
        //! @return The sprite font.
        [[nodiscard]] std::shared_ptr<SpriteFont> loadSnowBSpriteFont(
            const std::string &xmlPath,
            std::string texturePath = "") const;

    private:
        Framework &framework;

        std::shared_ptr<SpriteFont> createSnowBSpriteFont(
            tinyxml2::XMLNode &fontNode,
            const std::shared_ptr<Texture2D>& texture) const;
    };
}


#endif //SPRITEFONTLOADER_H
