//
// Created by Erkapic Luka on 2.4.2025.
//

#ifndef LDTK_LAYER_INSTANCE_H
#define LDTK_LAYER_INSTANCE_H

#include <cstdint>
#include <vector>
#include "asset_toolkit/ldtk/data/LdtkTileInstance.h"

namespace asset_toolkit {
    struct LdtkLayerInstance {

        //! The level id.
        uint32_t levelId;

        //! Grid-based height.
        uint32_t __cHei;

        //! Grid-based width.
        uint32_t __cWid;

        //! The relative path to corresponding Tileset, if any.
        std::string __tilesetRelPath;

        //! Layer instance visibility.
        bool visible;

        //! A list of all values in the IntGrid layer, stored in CSV format (Comma Separated Values). <br/>
        //! Order is from left to right, and top to bottom (i.e. first row from left to right, followed by second row, etc.). <br/>
        //! <code>0</code> means "empty cell" and IntGrid values start at 1. <br/>
        //! The array size is <code>__cWid</code> <b>x</b> <code>__cHei</code> cells.
        std::vector<int32_t> intGridCsv;

        //! An array containing all tiles generated by Auto-layer rules. The array is already sorted in display order
        //! (i.e. 1st tile is beneath 2nd, which is beneath 3rd etc.).
        //! <p>Note:</p>
        //! if multiple tiles are stacked in the same cell as the result of different rules, all tiles behind opaque ones will be discarded.
        std::vector<LdtkTileInstance> autoLayerTiles;

        //! An array containing all tiles generated by Grid layers. The array is already sorted in display order.
        std::vector<LdtkTileInstance> gridTiles;

    };
}

#endif //LDTK_LAYER_INSTANCE_H
